<a href="https://colab.research.google.com/github/ShivangiDatta/Assignment-IBM/blob/main/My_first_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **My First ML Project**

##Load Data

In [103]:
!pip install pandas

In [107]:
import pandas as pd
df = pd.read_csv('heart_2020_cleaned.csv')


In [108]:
df.head()

HeartDisease    BMI Smoking AlcoholDrinking Stroke  PhysicalHealth  \
0           No  16.60     Yes              No     No             3.0   
1           No  20.34      No              No    Yes             0.0   
2           No  26.58     Yes              No     No            20.0   
3           No  24.21      No              No     No             0.0   
4           No  23.71      No              No     No            28.0   

   MentalHealth DiffWalking     Sex  AgeCategory   Race Diabetic  \
0          30.0          No  Female        55-59  White      Yes   
1           0.0          No  Female  80 or older  White       No   
2          30.0          No    Male        65-69  White      Yes   
3           0.0          No  Female        75-79  White       No   
4           0.0         Yes  Female        40-44  White       No   

  PhysicalActivity  GenHealth  SleepTime Asthma KidneyDisease SkinCancer  
0              Yes  Very good        5.0    Yes            No        Yes  
1              Yes  Very good        7.0     No            No         No  
2              Yes       Fair        8.0    Yes            No         No  
3               No       Good        6.0     No            No        Yes  
4              Yes  Very good        8.0     No            No         No

In [137]:
df['HeartDisease'] = df['HeartDisease'].map({'Yes': 1.0, 'No': 0})
df

HeartDisease    BMI Smoking AlcoholDrinking Stroke  PhysicalHealth  \
0                0.0  16.60     Yes              No     No             3.0   
1                0.0  20.34      No              No    Yes             0.0   
2                0.0  26.58     Yes              No     No            20.0   
3                0.0  24.21      No              No     No             0.0   
4                0.0  23.71      No              No     No            28.0   
...              ...    ...     ...             ...    ...             ...   
319790           1.0  27.41     Yes              No     No             7.0   
319791           0.0  29.84     Yes              No     No             0.0   
319792           0.0  24.24      No              No     No             0.0   
319793           0.0  32.81      No              No     No             0.0   
319794           0.0  46.56      No              No     No             0.0   

        MentalHealth DiffWalking     Sex  AgeCategory      Race Diabetic  \
0               30.0          No  Female        55-59     White      Yes   
1                0.0          No  Female  80 or older     White       No   
2               30.0          No    Male        65-69     White      Yes   
3                0.0          No  Female        75-79     White       No   
4                0.0         Yes  Female        40-44     White       No   
...              ...         ...     ...          ...       ...      ...   
319790           0.0         Yes    Male        60-64  Hispanic      Yes   
319791           0.0          No    Male        35-39  Hispanic       No   
319792           0.0          No  Female        45-49  Hispanic       No   
319793           0.0          No  Female        25-29  Hispanic       No   
319794           0.0          No  Female  80 or older  Hispanic       No   

       PhysicalActivity  GenHealth  SleepTime Asthma KidneyDisease SkinCancer  
0                   Yes  Very good        5.0    Yes            No        Yes  
1                   Yes  Very good        7.0     No            No         No  
2                   Yes       Fair        8.0    Yes            No         No  
3                    No       Good        6.0     No            No        Yes  
4                   Yes  Very good        8.0     No            No         No  
...                 ...        ...        ...    ...           ...        ...  
319790               No       Fair        6.0    Yes            No         No  
319791              Yes  Very good        5.0    Yes            No         No  
319792              Yes       Good        6.0     No            No         No  
319793               No       Good       12.0     No            No         No  
319794              Yes       Good        8.0     No            No         No  

[319795 rows x 18 columns]

In [138]:
df.columns

Index(['HeartDisease', 'BMI', 'Smoking', 'AlcoholDrinking', 'Stroke',
       'PhysicalHealth', 'MentalHealth', 'DiffWalking', 'Sex', 'AgeCategory',
       'Race', 'Diabetic', 'PhysicalActivity', 'GenHealth', 'SleepTime',
       'Asthma', 'KidneyDisease', 'SkinCancer'],
      dtype='object')

##Data Preparation



In [139]:
y = df['HeartDisease']
y

0         0.0
1         0.0
2         0.0
3         0.0
4         0.0
         ... 
319790    1.0
319791    0.0
319792    0.0
319793    0.0
319794    0.0
Name: HeartDisease, Length: 319795, dtype: float64

In [140]:
X = df.drop(['HeartDisease', 'PhysicalHealth', 'MentalHealth','DiffWalking', 'Race', 'PhysicalActivity', 'GenHealth', 'Asthma', 'SkinCancer', 'AgeCategory', 'Sex', 'Diabetic'], axis=1)
X

BMI Smoking AlcoholDrinking Stroke  SleepTime KidneyDisease
0       16.60     Yes              No     No        5.0            No
1       20.34      No              No    Yes        7.0            No
2       26.58     Yes              No     No        8.0            No
3       24.21      No              No     No        6.0            No
4       23.71      No              No     No        8.0            No
...       ...     ...             ...    ...        ...           ...
319790  27.41     Yes              No     No        6.0            No
319791  29.84     Yes              No     No        5.0            No
319792  24.24      No              No     No        6.0            No
319793  32.81      No              No     No       12.0            No
319794  46.56      No              No     No        8.0            No

[319795 rows x 6 columns]

In [141]:
X.head(5)

BMI Smoking AlcoholDrinking Stroke  SleepTime KidneyDisease
0  16.60     Yes              No     No        5.0            No
1  20.34      No              No    Yes        7.0            No
2  26.58     Yes              No     No        8.0            No
3  24.21      No              No     No        6.0            No
4  23.71      No              No     No        8.0            No

In [142]:
X['Smoking'] = X['Smoking'].map({'Yes': 1.0, 'No': 0})
X['AlcoholDrinking'] = X['AlcoholDrinking'].map({'Yes': 1.0, 'No': 0})
X['Stroke'] = X['Stroke'].map({'Yes': 1.0, 'No': 0})
X['KidneyDisease'] = X['KidneyDisease'].map({'Yes': 1.0, 'No': 0})
X

BMI  Smoking  AlcoholDrinking  Stroke  SleepTime  KidneyDisease
0       16.60      1.0              0.0     0.0        5.0            0.0
1       20.34      0.0              0.0     1.0        7.0            0.0
2       26.58      1.0              0.0     0.0        8.0            0.0
3       24.21      0.0              0.0     0.0        6.0            0.0
4       23.71      0.0              0.0     0.0        8.0            0.0
...       ...      ...              ...     ...        ...            ...
319790  27.41      1.0              0.0     0.0        6.0            0.0
319791  29.84      1.0              0.0     0.0        5.0            0.0
319792  24.24      0.0              0.0     0.0        6.0            0.0
319793  32.81      0.0              0.0     0.0       12.0            0.0
319794  46.56      0.0              0.0     0.0        8.0            0.0

[319795 rows x 6 columns]

##Data Splitting

In [143]:

import numpy as np
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=100)

In [144]:
X_train

BMI  Smoking  AlcoholDrinking  Stroke  SleepTime  KidneyDisease
120475  30.68      0.0              0.0     0.0        6.0            0.0
212392  32.08      1.0              0.0     0.0        7.0            0.0
22254   28.80      0.0              0.0     0.0        6.0            0.0
29743   19.37      1.0              0.0     0.0        6.0            0.0
104580  46.11      0.0              0.0     0.0        6.0            0.0
...       ...      ...              ...     ...        ...            ...
65615   38.01      0.0              0.0     0.0        6.0            0.0
253799  19.37      1.0              1.0     0.0        6.0            0.0
210755  26.22      0.0              0.0     0.0        7.0            0.0
56088   31.47      0.0              0.0     0.0        8.0            0.0
300552  19.66      0.0              0.0     0.0        6.0            0.0

[255836 rows x 6 columns]

# **Model Building**

##Linear Regression

In [145]:
from sklearn.linear_model import LinearRegression

lr = LinearRegression()
lr.fit(X_train, y_train)

LinearRegression()

In [146]:
y_lr_train_pred = lr.predict(X_train)
y_lr_test_pred = lr.predict(X_test)

In [153]:
y_lr_train_pred

array([0.05111721, 0.11015255, 0.04786609, ..., 0.04502642, 0.05572732,
       0.03206011])

In [149]:
y_lr_test_pred

array([0.04189635, 0.07389234, 0.04407888, ..., 0.11351755, 0.03171425,
       0.03898751])

In [154]:
y_train

120475    1.0
212392    1.0
22254     0.0
29743     0.0
104580    0.0
         ... 
65615     0.0
253799    0.0
210755    0.0
56088     0.0
300552    0.0
Name: HeartDisease, Length: 255836, dtype: float64

In [155]:
y_lr_train_pred

array([0.05111721, 0.11015255, 0.04786609, ..., 0.04502642, 0.05572732,
       0.03206011])